### ISSUE TITLE
Lambda function fails during test

### ISSUE THREAD

**Issue by sandeepmendiratta** [Notalifeform/arlo-timelapse-lambda#1]
After I create a new lambda function and test I am getting following error. Have you seen this or know what could cause this. I am able to run locally fine.

``` An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/arlosnapshot.py", line 33, in lambda_handler
s3.Bucket(S3_BUCKET_NAME).download_file('sequence.txt', '/tmp/sequence.txt')
File "/var/task/boto3/s3/inject.py", line 246, in bucket_download_file
ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
File "/var/task/boto3/s3/inject.py", line 172, in download_file
extra_args=ExtraArgs, callback=Callback)
File "/var/task/boto3/s3/transfer.py", line 307, in download_file
future.result()
File "/var/task/s3transfer/futures.py", line 73, in result
return self._coordinator.result()
File "/var/task/s3transfer/futures.py", line 233, in result
raise self._exception
File "/var/task/s3transfer/tasks.py", line 255, in _main
self._submit(transfer_future=transfer_future, **kwargs)
File "/var/task/s3transfer/download.py", line 353, in _submit
**transfer_future.meta.call_args.extra_args
File "/var/task/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/botocore/client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden ```

**Comment by sandeepmendiratta** [comment]
@Notalifeform ^^^

**Comment by Notalifeform** [comment]
Hi @sandeepmendiratta  did you set up S3 access properly?
You should give your lambda the proper rights, as I did here:
![image](https://user-images.githubusercontent.com/429676/50493549-83520d00-0a1e-11e9-9f09-a48622e8ac6b.png)

**Comment by sandeepmendiratta** [comment]
Thanks for the reply. Changing S3 permissions  did fix the 403 error. Now when I run the test it is timing out with following.
``` START RequestId: 7625383c-0a51-11e9-a486-ab69638cb57b Version: $LATEST
Looking up sequence number
Creating ARLO snapshot 10
END RequestId: 7625383c-0a51-11e9-a486-ab69638cb57b
REPORT RequestId: 7625383c-0a51-11e9-a486-ab69638cb57b	Duration: 3003.32 ms	Billed Duration: 3000 ms 	Memory Size: 128 MB	Max Memory Used: 46 MB	
2018-12-28T03:34:23.257Z 7625383c-0a51-11e9-a486-ab69638cb57b Task timed out after 3.00 seconds ```

**Comment by Notalifeform** [comment]
for arlo 3 seconds is too short - please up it to 30 seconds

**Comment by sandeepmendiratta** [comment]
@Notalifeform Thank you! Everything is working great.
